version: '3.0'


services:
  app:
    container_name: app
    build:
      context: .
    env_file:
      - .env
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - .:/app
      # Исключение директории из volume чтобы не мешала разработке
      - /app/venv
    restart: always
    command: ./run
    depends_on:
      - db
      - redis
      - weather-service

  db:
    container_name: db
    image: postgres:16
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    container_name: redis
    image: redis:7
    # Бэкап каждые 4 минуты
    command: redis-server --save 240 1 --loglevel warning
    volumes:
      - redis_data:/data
    restart: always

  celery:
    restart: always
    build:
      context: .
    command: celery -A core worker -l info
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - app

  celery-beat:
    restart: always
    build:
      context: .
    command: celery -A core beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - app
      - celery

  weather-service:
    restart: always
    build:
      context: .
    command: uvicorn weather_service.app:app --host 0.0.0.0 --port 80
    env_file:
      - .env

volumes:
  postgres_data:
  redis_data:
