#!/bin/bash
python manage.py createsuperuser --no-input 2>/dev/null || echo "Superuser already exists"
python manage.py migrate
python manage.py collectstatic --no-input
if [[ "$DEBUG" == "True" ]]; then
  python manage.py runserver $APP_HOST:$APP_PORT
else
  gunicorn --workers=4 -b $APP_HOST:$APP_PORT core.wsgi
fi
