# Generated by Django 4.2 on 2023-12-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
