# Generated by Django 4.2 on 2023-12-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_place_latitude_alter_place_longitude'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='place',
            constraint=models.CheckConstraint(check=models.Q(('rating__range', (0, 25))), name='rating_constraint'),
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.CheckConstraint(check=models.Q(('latitude__range', (-90, 90))), name='latitude_constraint'),
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.CheckConstraint(check=models.Q(('longitude__range', (-180, 180))), name='longitude_constraint'),
        ),
    ]
